package database;

import constants.Database;
import models.users.User;
import utils.TokenCreator;

import java.sql.*;

import static database.DAOUtilities.*;

/**
 * Created by mrmmtb on 25.04.16.
 */
public class UsersDAOImpl implements  UsersDAO {

    private DAOFactory daoFactory;
    private TokenCreator tokenCreator;

    UsersDAOImpl(DAOFactory daoFactory) {
        this.daoFactory = daoFactory;
        this.tokenCreator = new TokenCreator();
    }


    @Override
    public boolean create(User user){
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        ResultSet autoGeneratedValues = null;
        boolean error = false;
        String token = this.tokenCreator.newToken();
        boolean accountValidated = false;
        try {
            connection = daoFactory.getConnection();
            preparedStatement = initializationPreparedRequest( connection, Database.SQL_INSERT, true,
                                                               user.getFirstName(), user.getLastName(),
                                                               user.getUsername(), user.getEmail()
                                                             );
            int statut = preparedStatement.executeUpdate();
            if ( statut == 0 ) {
                System.err.println("Failed to create a user, no new line added to the table.");
            }
            autoGeneratedValues = preparedStatement.getGeneratedKeys();
            if ( autoGeneratedValues.next() ) {
                user.setId( autoGeneratedValues.getInt( 1 ) );
            }
            else {
               System.err.println("Failed to create a user, no auto-generated ID returned." );
            }
        }
        catch (SQLIntegrityConstraintViolationException e){
            System.out.print("Failed to create a user, username or email already exists\n");
            error = true;
        }
        catch ( SQLException e ) {
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
        }
        finally {
            silentClosures( autoGeneratedValues, preparedStatement, connection );
        }
        return error;
    }

    @Override
    public User findByUsername(String username) {
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        User user = null;
        try {
            connection = daoFactory.getConnection();
            preparedStatement = initializationPreparedRequest( connection, Database.SQL_SELECT_BY_USERNAME,
                                                               false, username );
            resultSet = preparedStatement.executeQuery();
            if ( resultSet.next() ) {
                user = map( resultSet );
            }
        } catch ( SQLException e ) {
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
        } finally {
            silentClosures( resultSet, preparedStatement, connection );
        }

        return user;
    }

    @Override
    public User findByUsernameAndPassword(String username, String password) {
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        User user = null;
        try {
            connection = daoFactory.getConnection();
            preparedStatement = initializationPreparedRequest(connection, Database.SQL_MATCH_USERNAME_PASSWORD,
                                                              false, username, password);
            resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {
                user = findByUsername(username);
            }
        }catch (SQLException e) {
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
        }finally {
            silentClosures( resultSet, preparedStatement, connection );
        }
        return user;
    }

    @Override
    public void setPasswordToUser(User user, String password) {
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        try {
            connection = daoFactory.getConnection();
            preparedStatement = initializationPreparedRequest( connection, Database.SQL_SET_PASSWORD_TO_USER, false,
                                                               password, user.getUsername() );
            int statut = preparedStatement.executeUpdate();
            if ( statut == 0 ) {
               System.err.println( "Failed to update user's password" );
            }
        } catch ( SQLException e ) {
            System.err.println( "Failed to update user's password" );
        } finally {
            silentClosures( preparedStatement, connection );
        }
    }


    private static User map(ResultSet resultSet) throws SQLException {
        int id = resultSet.getInt("id");
        String first_name = resultSet.getString("first_name");
        String last_name = resultSet.getString("last_name");
        String username = resultSet.getString("username");
        String email = resultSet.getString("email");
        return new User(id, first_name, last_name, username, email);
    }
}
